marina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls', namespace='quiz')),
]

quiz/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create', views.QuestionCreate.as_view(), name='create'),
    path('training', views.TrainingView.as_view(), name='training'),
    path('question', views.QuestionView.as_view(), name='question'),
]

quiz/models.py
from django.db import models


class QuestionTheme(models.Model):
    title = models.CharField(max_length=75)

    def __str__(self):
        return self.title


class Question(models.Model):
    theme = models.ForeignKey(QuestionTheme, on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField('Question')
    answer = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

quiz/forms.py
from django import forms

from quiz.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'answer']


class QuizForm(forms.Form):
    answer = forms.CharField(widget=forms.Textarea)

quiz/views.py
import random

from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView

from quiz.forms import QuizForm
from quiz.models import Question


class IndexView(TemplateView):
    template_name = 'quiz/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions_count'] = Question.objects.count()
        return context


class QuestionCreate(CreateView):
    template_name = 'quiz/create.html'
    model = Question
    fields = ['text', 'answer']
    success_url = reverse_lazy('quiz:create')


class TrainingView(View):
    def get(self, request):
        form = QuizForm()
        context = {
            'form': form,
        }
        return render(request, 'quiz/training.html', context)


class QuestionView(View):
    def get(self, request):
        print(request.COOKIES)
        questions = Question.objects.all()
        if questions.count() > 1:
            while True:
                question = random.choice(questions)
                if request.session.get('question_id') != question.id:
                    break
        else:
            question = questions.first()
        request.session['question_id'] = question.id
        data = {
            'question': question.text,
            'answer': question.answer,
        }
        return JsonResponse(data)

quiz/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Marina</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>

    {% block scripts %}
    {% endblock %}
  </body>
</html>

quiz/templates/quiz/create.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
<a href="{% url 'quiz:index' %}">Home</a>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello from Marina</h1>
    <p>
        Questions: {{ questions_count }}
        <a href="#">View</a>
        <a href="{% url 'quiz:create' %}">Add</a>
    </p>
    <p>
        <a href="{% url 'quiz:training' %}">Training</a>
    </p>
{% endblock content %}

quiz/templates/quiz/training.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Training</h1>
    <div id="training-app">
        <div class="row">
            <div id="question">${ question }</div>
        </div>
        <div class="row">
            <div class="col">
                <div id="quiz_form">
                    <div class="form-group">
                        <textarea name="answer" cols="40" rows="10" id="id_answer" class="form-control"
                        v-model="userAnswer"></textarea>
                    </div>
                    <button id="skip" class="btn btn-secondary" v-on:click="skipQuestion">Skip</button>
                    <button class="btn btn-success" v-on:click="checkAnswer">Check</button>
                </div>
            </div>
            <div class="col" v-on:click="toggleAnswerVisible">
                <div class="answer"
                    v-if="answerIsVisible"
                >
                    ${ answer }
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% load static %}
<script>
    const URL = "{% url 'quiz:question' %}";
</script>
<script src="{% static '/quiz/training.js' %}">
</script>
{% endblock %}